### ISSUE TITLE
Add badges to README.md

### ISSUE THREAD

**Issue by melonpii** [VSangarya/AMATSA#18]
Badges for build, code coverage, doi are a must. Feel free to improvise and add more cool stuff!

**Comment by atharv67** [comment]
I'll start working on this

**Comment by atharv67** [comment]
@VSangarya Please add the DOI badge

**Comment by atharv67** [comment]
Add open issues badge, repo size, python version, release.

**Comment by melonpii** [comment]
Assigning it to @VSangarya for doi badge when we are complete with 1st release work.

**Comment by atharv67** [comment]
All badges done
