### ISSUE TITLE
Generate code documentation

### ISSUE THREAD

**Issue by melonpii** [VSangarya/AMATSA#19]
Generate docs for code using some tool. https://docs.python.org/3/library/pydoc.html is a good source to read about.

**Comment by qureshi-ali** [comment]
Will start working on this.

**Comment by qureshi-ali** [comment]
which folder does the documentation go in ?

**Comment by melonpii** [comment]
docs/ in root directory. You might have to go through the code-bits and add comments to make it work!

**Comment by melonpii** [comment]
Closing issue as #42 resolves this
