### ISSUE TITLE
IP Address and hostname considerations

### ISSUE THREAD

**Issue by melonpii** [VSangarya/AMATSA#24]
Expected: It should generate primary interface address like 192.168.1.21 etc.

We already have hostname in system info. Instead of socket.gethostbyname, we can have socket.fqdn in network side. What's your take on this?

**Comment by shivangichopra10** [comment]
the functionality seems to be working fine on a windows system. will check for system dependency of functionality.

**Comment by melonpii** [comment]
Works now without any change. Seems to have been an issue on my side. Apologies.
