### ISSUE TITLE
Get disk info instead of partitions on macOS

### ISSUE THREAD

**Issue by melonpii** [VSangarya/AMATSA#27]
We are seeing partitions in disks category. Investigate if we can see disk info here.

Issue: If there is 1 disk with 3 partitions, we get 3 disk entries with partition name + disk size.
Expected: We should see 1 disk entry with disk name + disk size.

**Comment by VSangarya** [comment]
All the disk sizes data summed into one ?

**Comment by melonpii** [comment]
Noticed this issue only with macos systems. Windows/Linux seem to be fine.
