### ISSUE TITLE
Data point to collect from clients

### ISSUE THREAD

**Issue by melonpii** [VSangarya/AMATSA#6]

**Comment by VSangarya** [comment]
Possible data points to collect :-
- Hostname
- OS
- OS version/kernel version
- Total disk space
- Available disk space
- IP address
- Open ports
- Current running processes/applications
- Battery percentage
- Current memory cache size
- Current CPU utilization
- Average CPU speed
- Current Memory utilization
- Current Network utilization
- Network send/receive speeds
- Users
- System up time


Slightly advanced:
- Peak CPU utilization's timestamp and metric over last "x" hours
- Peak Memory utilization's timestamp and metric over last "x" hours
- Peak Network utilization's timestamp and metric over last "x" hours
- CPU core temperature
- Total CPU utilization over the last "x" hours
- Average CPU speed over the last "x" hours
- Total Memory utilization over the last "x" hours
- Total Network utilization over the last "x" hours


If GPU exists:
- Total GPU utilization over the last "x" hours
- Total GPU memory space
- GPU memory space available

**Comment by atharv67** [comment]
Time series based data-points like:
- How CPU utilization has changed over the last hour. 
We can then create a dashboard where the admin can select the client/ group of clients and view these data-points

**Comment by melonpii** [comment]
Let us also study the feasibility of collecting this information using Python libs. Prefer standard libs to be cross-platform as much as possible!

**Comment by VSangarya** [comment]
Additional fields:
- MAC Address
- IP Address : Private and public IP
- Number of CPU cores
- Number of partitions of disk

**Comment by melonpii** [comment]
We need something to identify a machine uniquely. Something like a BIOS UUID.

**Comment by VSangarya** [comment]
Will explore on that

**Comment by atharv67** [comment]
> Let us also study the feasibility of collecting this information using Python libs. Prefer standard libs to be cross-platform as much as possible!

I glanced through the doco for os and sys lib. I don't think getting all information using it will be possible, we will need additional modules.

**Comment by atharv67** [comment]
> We need something to identify a machine uniquely. Something like a BIOS UUID.

Can we write code that uniquely identifies the client the first time we push its data onto elastic and use that same id always. Can be like "Client_1, Client_2..., Client_n?"

**Comment by shivangichopra10** [comment]
> We need something to identify a machine uniquely. Something like a BIOS UUID.

We can check if machine identification with MAC Address should work for us.

**Comment by melonpii** [comment]
Closing issue as this task is complete.
